[profile.dev]
opt-level = 0 # none
debug-assertions = true
debug = true
incremental = true

[profile.release]
strip = true
opt-level = 3 # all
debug-assertions = false
lto = true
codegen-units = 1

[workspace]
members = [
	"src/lib",
    "src/tools/texture-unstitcher",
    "src/tools/observer"
]